# This file was generated by swiftpm2nix.
{
  workspaceStateFile = ./workspace-state.json;
  hashes = {
    "adwaita-swift" = "18ij2vrglfxipid4qx6xgd5yich3vqqnq26k9d912sm00hkvyc88";
    "LevenshteinTransformations" = "0bgkx4x1dbsi9sxj37x8h9c7jgv57f20vlry2wcwymm1j865wg2s";
    "swift-atomics" = "0rzq9klikwm4jv9y0wqb2wajlv6nlcyjgg5bvf35209h6l2gz38y";
    "swift-dns-service-discovery" = "0a5k2i6fmra7p88hd0h5i6zkkdi8bq62yv2ilfwsj18l73g6raqc";
    "swift-log" = "00fp20dxh97fabxbag8a21hl3gp45lkrvr2gh01f0ssjnd1zsmk0";
    "swift-service-discovery" = "0wgkaxjqviwglrqiwb1vhm8sghx6zyvvg5fs5q7d1ar5y9ps0lwd";
  };
}
